/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice Branch L</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globalTypes.myDsl.ChoiceBranchL#getMessage <em>Message</em>}</li>
 *   <li>{@link org.xtext.globalTypes.myDsl.ChoiceBranchL#getProtocol <em>Protocol</em>}</li>
 * </ul>
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoiceBranchL()
 * @model
 * @generated
 */
public interface ChoiceBranchL extends EObject
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' containment reference.
   * @see #setMessage(MessageL)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoiceBranchL_Message()
   * @model containment="true"
   * @generated
   */
  MessageL getMessage();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.ChoiceBranchL#getMessage <em>Message</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' containment reference.
   * @see #getMessage()
   * @generated
   */
  void setMessage(MessageL value);

  /**
   * Returns the value of the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' containment reference.
   * @see #setProtocol(ProtocolL)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoiceBranchL_Protocol()
   * @model containment="true"
   * @generated
   */
  ProtocolL getProtocol();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.ChoiceBranchL#getProtocol <em>Protocol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' containment reference.
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(ProtocolL value);

} // ChoiceBranchL
