/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globalTypes.myDsl.Choice#getRole <em>Role</em>}</li>
 *   <li>{@link org.xtext.globalTypes.myDsl.Choice#getBranches <em>Branches</em>}</li>
 * </ul>
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoice()
 * @model
 * @generated
 */
public interface Choice extends EObject
{
  /**
   * Returns the value of the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' reference.
   * @see #setRole(RoleOne)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoice_Role()
   * @model
   * @generated
   */
  RoleOne getRole();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.Choice#getRole <em>Role</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' reference.
   * @see #getRole()
   * @generated
   */
  void setRole(RoleOne value);

  /**
   * Returns the value of the '<em><b>Branches</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.globalTypes.myDsl.Message}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Branches</em>' containment reference list.
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getChoice_Branches()
   * @model containment="true"
   * @generated
   */
  EList<Message> getBranches();

} // Choice
