/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globalTypes.myDsl.Message#getMessageType <em>Message Type</em>}</li>
 *   <li>{@link org.xtext.globalTypes.myDsl.Message#getPayload <em>Payload</em>}</li>
 *   <li>{@link org.xtext.globalTypes.myDsl.Message#getSender <em>Sender</em>}</li>
 *   <li>{@link org.xtext.globalTypes.myDsl.Message#getReceiver <em>Receiver</em>}</li>
 * </ul>
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getMessage()
 * @model
 * @generated
 */
public interface Message extends EObject
{
  /**
   * Returns the value of the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message Type</em>' attribute.
   * @see #setMessageType(String)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getMessage_MessageType()
   * @model
   * @generated
   */
  String getMessageType();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.Message#getMessageType <em>Message Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message Type</em>' attribute.
   * @see #getMessageType()
   * @generated
   */
  void setMessageType(String value);

  /**
   * Returns the value of the '<em><b>Payload</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Payload</em>' containment reference.
   * @see #setPayload(Payload)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getMessage_Payload()
   * @model containment="true"
   * @generated
   */
  Payload getPayload();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.Message#getPayload <em>Payload</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Payload</em>' containment reference.
   * @see #getPayload()
   * @generated
   */
  void setPayload(Payload value);

  /**
   * Returns the value of the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sender</em>' reference.
   * @see #setSender(RoleOne)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getMessage_Sender()
   * @model
   * @generated
   */
  RoleOne getSender();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.Message#getSender <em>Sender</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sender</em>' reference.
   * @see #getSender()
   * @generated
   */
  void setSender(RoleOne value);

  /**
   * Returns the value of the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Receiver</em>' reference.
   * @see #setReceiver(RoleOne)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getMessage_Receiver()
   * @model
   * @generated
   */
  RoleOne getReceiver();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.Message#getReceiver <em>Receiver</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Receiver</em>' reference.
   * @see #getReceiver()
   * @generated
   */
  void setReceiver(RoleOne value);

} // Message
