/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.globalTypes.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/globalTypes/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ModelImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Protocol Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROTOCOL_NAME = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ROLES = 1;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROTOCOL = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RolesImpl <em>Roles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RolesImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoles()
   * @generated
   */
  int ROLES = 1;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLES__ROLES = 0;

  /**
   * The number of structural features of the '<em>Roles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRole()
   * @generated
   */
  int ROLE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleOneImpl <em>Role One</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleOneImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleOne()
   * @generated
   */
  int ROLE_ONE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_ONE__NAME = ROLE__NAME;

  /**
   * The number of structural features of the '<em>Role One</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_ONE_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleMultipleImpl <em>Role Multiple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleMultipleImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleMultiple()
   * @generated
   */
  int ROLE_MULTIPLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_MULTIPLE__NAME = ROLE__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_MULTIPLE__REF = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Role Multiple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_MULTIPLE_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolImpl <em>Protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ProtocolImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocol()
   * @generated
   */
  int PROTOCOL = 5;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL__ACTIONS = 0;

  /**
   * The number of structural features of the '<em>Protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionImpl <em>Recursion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RecursionImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursion()
   * @generated
   */
  int RECURSION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION__NAME = 0;

  /**
   * The number of structural features of the '<em>Recursion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl <em>Close Recursion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursion()
   * @generated
   */
  int CLOSE_RECURSION = 7;

  /**
   * The feature id for the '<em><b>Recursion Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION__RECURSION_VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Close Recursion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ForEachImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEach()
   * @generated
   */
  int FOR_EACH = 8;

  /**
   * The feature id for the '<em><b>Each Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__EACH_ROLE = 0;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__ROLE = 1;

  /**
   * The feature id for the '<em><b>Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__BRANCH = 2;

  /**
   * The number of structural features of the '<em>For Each</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ChoiceImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 9;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__ROLE = 0;

  /**
   * The feature id for the '<em><b>Message</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__MESSAGE = 1;

  /**
   * The feature id for the '<em><b>Branch</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__BRANCH = 2;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 10;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MESSAGE_TYPE = 0;

  /**
   * The feature id for the '<em><b>Payload</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__PAYLOAD = 1;

  /**
   * The feature id for the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__SENDER = 2;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__RECEIVER = 3;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.PayloadImpl <em>Payload</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.PayloadImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getPayload()
   * @generated
   */
  int PAYLOAD = 11;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD__TYPES = 0;

  /**
   * The number of structural features of the '<em>Payload</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.globalTypes.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Model#getProtocolName <em>Protocol Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol Name</em>'.
   * @see org.xtext.globalTypes.myDsl.Model#getProtocolName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_ProtocolName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Model#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.Model#getRoles()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Roles();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Model#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.Model#getProtocol()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Roles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.Roles
   * @generated
   */
  EClass getRoles();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Roles#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.Roles#getRoles()
   * @see #getRoles()
   * @generated
   */
  EReference getRoles_Roles();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Role#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globalTypes.myDsl.Role#getName()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.RoleOne <em>Role One</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role One</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleOne
   * @generated
   */
  EClass getRoleOne();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.RoleMultiple <em>Role Multiple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role Multiple</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleMultiple
   * @generated
   */
  EClass getRoleMultiple();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.RoleMultiple#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleMultiple#getRef()
   * @see #getRoleMultiple()
   * @generated
   */
  EReference getRoleMultiple_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Protocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.Protocol
   * @generated
   */
  EClass getProtocol();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Protocol#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.xtext.globalTypes.myDsl.Protocol#getActions()
   * @see #getProtocol()
   * @generated
   */
  EReference getProtocol_Actions();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Recursion <em>Recursion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recursion</em>'.
   * @see org.xtext.globalTypes.myDsl.Recursion
   * @generated
   */
  EClass getRecursion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Recursion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globalTypes.myDsl.Recursion#getName()
   * @see #getRecursion()
   * @generated
   */
  EAttribute getRecursion_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.CloseRecursion <em>Close Recursion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close Recursion</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursion
   * @generated
   */
  EClass getCloseRecursion();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.CloseRecursion#getRecursionVariable <em>Recursion Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Recursion Variable</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursion#getRecursionVariable()
   * @see #getCloseRecursion()
   * @generated
   */
  EReference getCloseRecursion_RecursionVariable();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ForEach <em>For Each</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Each</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach
   * @generated
   */
  EClass getForEach();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEach#getEachRole <em>Each Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Each Role</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getEachRole()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_EachRole();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ForEach#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getRole()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Role();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEach#getBranch <em>Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Branch</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getBranch()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Branch();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Choice#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice#getRole()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Role();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Choice#getMessage <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Message</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice#getMessage()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Message();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Choice#getBranch <em>Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Branch</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice#getBranch()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Branch();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see org.xtext.globalTypes.myDsl.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Message#getMessageType <em>Message Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message Type</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getMessageType()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_MessageType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Message#getPayload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Payload</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getPayload()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Payload();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Message#getSender <em>Sender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sender</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getSender()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Sender();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Message#getReceiver <em>Receiver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Receiver</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getReceiver()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Receiver();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Payload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payload</em>'.
   * @see org.xtext.globalTypes.myDsl.Payload
   * @generated
   */
  EClass getPayload();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.globalTypes.myDsl.Payload#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see org.xtext.globalTypes.myDsl.Payload#getTypes()
   * @see #getPayload()
   * @generated
   */
  EAttribute getPayload_Types();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ModelImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Protocol Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__PROTOCOL_NAME = eINSTANCE.getModel_ProtocolName();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ROLES = eINSTANCE.getModel_Roles();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROTOCOL = eINSTANCE.getModel_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RolesImpl <em>Roles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RolesImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoles()
     * @generated
     */
    EClass ROLES = eINSTANCE.getRoles();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLES__ROLES = eINSTANCE.getRoles_Roles();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__NAME = eINSTANCE.getRole_Name();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleOneImpl <em>Role One</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleOneImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleOne()
     * @generated
     */
    EClass ROLE_ONE = eINSTANCE.getRoleOne();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleMultipleImpl <em>Role Multiple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleMultipleImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleMultiple()
     * @generated
     */
    EClass ROLE_MULTIPLE = eINSTANCE.getRoleMultiple();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLE_MULTIPLE__REF = eINSTANCE.getRoleMultiple_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolImpl <em>Protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ProtocolImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocol()
     * @generated
     */
    EClass PROTOCOL = eINSTANCE.getProtocol();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOL__ACTIONS = eINSTANCE.getProtocol_Actions();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionImpl <em>Recursion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RecursionImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursion()
     * @generated
     */
    EClass RECURSION = eINSTANCE.getRecursion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECURSION__NAME = eINSTANCE.getRecursion_Name();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl <em>Close Recursion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursion()
     * @generated
     */
    EClass CLOSE_RECURSION = eINSTANCE.getCloseRecursion();

    /**
     * The meta object literal for the '<em><b>Recursion Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLOSE_RECURSION__RECURSION_VARIABLE = eINSTANCE.getCloseRecursion_RecursionVariable();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ForEachImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEach()
     * @generated
     */
    EClass FOR_EACH = eINSTANCE.getForEach();

    /**
     * The meta object literal for the '<em><b>Each Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__EACH_ROLE = eINSTANCE.getForEach_EachRole();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__ROLE = eINSTANCE.getForEach_Role();

    /**
     * The meta object literal for the '<em><b>Branch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__BRANCH = eINSTANCE.getForEach_Branch();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ChoiceImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__ROLE = eINSTANCE.getChoice_Role();

    /**
     * The meta object literal for the '<em><b>Message</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__MESSAGE = eINSTANCE.getChoice_Message();

    /**
     * The meta object literal for the '<em><b>Branch</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__BRANCH = eINSTANCE.getChoice_Branch();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Message Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MESSAGE_TYPE = eINSTANCE.getMessage_MessageType();

    /**
     * The meta object literal for the '<em><b>Payload</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__PAYLOAD = eINSTANCE.getMessage_Payload();

    /**
     * The meta object literal for the '<em><b>Sender</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__SENDER = eINSTANCE.getMessage_Sender();

    /**
     * The meta object literal for the '<em><b>Receiver</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__RECEIVER = eINSTANCE.getMessage_Receiver();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.PayloadImpl <em>Payload</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.PayloadImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getPayload()
     * @generated
     */
    EClass PAYLOAD = eINSTANCE.getPayload();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYLOAD__TYPES = eINSTANCE.getPayload_Types();

  }

} //MyDslPackage
