/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.globalTypes.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/globalTypes/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ModelImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__PROTOCOL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.GlobalProtocolImpl <em>Global Protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.GlobalProtocolImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getGlobalProtocol()
   * @generated
   */
  int GLOBAL_PROTOCOL = 1;

  /**
   * The feature id for the '<em><b>Protocol Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_PROTOCOL__PROTOCOL_NAME = 0;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_PROTOCOL__ROLES = 1;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_PROTOCOL__PROTOCOL = 2;

  /**
   * The number of structural features of the '<em>Global Protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GLOBAL_PROTOCOL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RolesImpl <em>Roles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RolesImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoles()
   * @generated
   */
  int ROLES = 2;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLES__ROLES = 0;

  /**
   * The number of structural features of the '<em>Roles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleImpl <em>Role</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRole()
   * @generated
   */
  int ROLE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Role</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleOneImpl <em>Role One</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleOneImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleOne()
   * @generated
   */
  int ROLE_ONE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_ONE__NAME = ROLE__NAME;

  /**
   * The number of structural features of the '<em>Role One</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_ONE_FEATURE_COUNT = ROLE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RoleSetImpl <em>Role Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RoleSetImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleSet()
   * @generated
   */
  int ROLE_SET = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_SET__NAME = ROLE__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_SET__REF = ROLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Role Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROLE_SET_FEATURE_COUNT = ROLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolImpl <em>Protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ProtocolImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocol()
   * @generated
   */
  int PROTOCOL = 6;

  /**
   * The feature id for the '<em><b>Begin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL__BEGIN = 0;

  /**
   * The number of structural features of the '<em>Protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.EndProtocolImpl <em>End Protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.EndProtocolImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getEndProtocol()
   * @generated
   */
  int END_PROTOCOL = 7;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_PROTOCOL__END = 0;

  /**
   * The number of structural features of the '<em>End Protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_PROTOCOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionImpl <em>Recursion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RecursionImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursion()
   * @generated
   */
  int RECURSION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Rec Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION__REC_PROTOCOL = 1;

  /**
   * The number of structural features of the '<em>Recursion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl <em>Close Recursion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursion()
   * @generated
   */
  int CLOSE_RECURSION = 9;

  /**
   * The feature id for the '<em><b>Recursion Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION__RECURSION_VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Close Recursion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ForEachImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEach()
   * @generated
   */
  int FOR_EACH = 10;

  /**
   * The feature id for the '<em><b>Loop Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__LOOP_ROLE = 0;

  /**
   * The feature id for the '<em><b>Roleset</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__ROLESET = 1;

  /**
   * The feature id for the '<em><b>Ref Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__REF_ROLE = 2;

  /**
   * The feature id for the '<em><b>For Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__FOR_BODY = 3;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__PROTOCOL = 4;

  /**
   * The number of structural features of the '<em>For Each</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ChoiceImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 11;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__ROLE = 0;

  /**
   * The feature id for the '<em><b>Branches</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__BRANCHES = 1;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageImpl <em>Message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessage()
   * @generated
   */
  int MESSAGE = 12;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MESSAGE_TYPE = 0;

  /**
   * The feature id for the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__SENDER = 1;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__RECEIVER = 2;

  /**
   * The number of structural features of the '<em>Message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageNormalImpl <em>Message Normal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageNormalImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageNormal()
   * @generated
   */
  int MESSAGE_NORMAL = 13;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL__MESSAGE_TYPE = MESSAGE__MESSAGE_TYPE;

  /**
   * The feature id for the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL__SENDER = MESSAGE__SENDER;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL__RECEIVER = MESSAGE__RECEIVER;

  /**
   * The feature id for the '<em><b>Payload</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL__PAYLOAD = MESSAGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL__PROTOCOL = MESSAGE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Message Normal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_FEATURE_COUNT = MESSAGE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageQuitImpl <em>Message Quit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageQuitImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageQuit()
   * @generated
   */
  int MESSAGE_QUIT = 14;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT__MESSAGE_TYPE = MESSAGE__MESSAGE_TYPE;

  /**
   * The feature id for the '<em><b>Sender</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT__SENDER = MESSAGE__SENDER;

  /**
   * The feature id for the '<em><b>Receiver</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT__RECEIVER = MESSAGE__RECEIVER;

  /**
   * The number of structural features of the '<em>Message Quit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT_FEATURE_COUNT = MESSAGE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.PayloadImpl <em>Payload</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.PayloadImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getPayload()
   * @generated
   */
  int PAYLOAD = 15;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD__TYPES = 0;

  /**
   * The number of structural features of the '<em>Payload</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAYLOAD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.LocalProtocolImpl <em>Local Protocol</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.LocalProtocolImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getLocalProtocol()
   * @generated
   */
  int LOCAL_PROTOCOL = 16;

  /**
   * The feature id for the '<em><b>Protocol Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_PROTOCOL__PROTOCOL_NAME = 0;

  /**
   * The feature id for the '<em><b>Projected Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_PROTOCOL__PROJECTED_ROLE = 1;

  /**
   * The feature id for the '<em><b>Roles</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_PROTOCOL__ROLES = 2;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_PROTOCOL__PROTOCOL = 3;

  /**
   * The number of structural features of the '<em>Local Protocol</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_PROTOCOL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolLImpl <em>Protocol L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ProtocolLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocolL()
   * @generated
   */
  int PROTOCOL_L = 17;

  /**
   * The feature id for the '<em><b>Begin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL_L__BEGIN = 0;

  /**
   * The number of structural features of the '<em>Protocol L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROTOCOL_L_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionLImpl <em>Recursion L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.RecursionLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursionL()
   * @generated
   */
  int RECURSION_L = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION_L__NAME = 0;

  /**
   * The feature id for the '<em><b>Rec Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION_L__REC_PROTOCOL = 1;

  /**
   * The number of structural features of the '<em>Recursion L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECURSION_L_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionLImpl <em>Close Recursion L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursionL()
   * @generated
   */
  int CLOSE_RECURSION_L = 19;

  /**
   * The feature id for the '<em><b>Recursion Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION_L__RECURSION_VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Close Recursion L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLOSE_RECURSION_L_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageLImpl <em>Message L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageL()
   * @generated
   */
  int MESSAGE_L = 20;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_L__MESSAGE_TYPE = 0;

  /**
   * The feature id for the '<em><b>Send Receive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_L__SEND_RECEIVE = 1;

  /**
   * The number of structural features of the '<em>Message L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_L_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageNormalLImpl <em>Message Normal L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageNormalLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageNormalL()
   * @generated
   */
  int MESSAGE_NORMAL_L = 21;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_L__MESSAGE_TYPE = MESSAGE_L__MESSAGE_TYPE;

  /**
   * The feature id for the '<em><b>Send Receive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_L__SEND_RECEIVE = MESSAGE_L__SEND_RECEIVE;

  /**
   * The feature id for the '<em><b>Payload</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_L__PAYLOAD = MESSAGE_L_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_L__PROTOCOL = MESSAGE_L_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Message Normal L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_NORMAL_L_FEATURE_COUNT = MESSAGE_L_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageQuitLImpl <em>Message Quit L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageQuitLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageQuitL()
   * @generated
   */
  int MESSAGE_QUIT_L = 22;

  /**
   * The feature id for the '<em><b>Message Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT_L__MESSAGE_TYPE = MESSAGE_L__MESSAGE_TYPE;

  /**
   * The feature id for the '<em><b>Send Receive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT_L__SEND_RECEIVE = MESSAGE_L__SEND_RECEIVE;

  /**
   * The number of structural features of the '<em>Message Quit L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_QUIT_L_FEATURE_COUNT = MESSAGE_L_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.MessageTypeImpl <em>Message Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.MessageTypeImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageType()
   * @generated
   */
  int MESSAGE_TYPE = 23;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TYPE__ROLE = 0;

  /**
   * The number of structural features of the '<em>Message Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.SenderLImpl <em>Sender L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.SenderLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getSenderL()
   * @generated
   */
  int SENDER_L = 24;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENDER_L__ROLE = MESSAGE_TYPE__ROLE;

  /**
   * The number of structural features of the '<em>Sender L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENDER_L_FEATURE_COUNT = MESSAGE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ReceiverLImpl <em>Receiver L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ReceiverLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getReceiverL()
   * @generated
   */
  int RECEIVER_L = 25;

  /**
   * The feature id for the '<em><b>Role</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECEIVER_L__ROLE = MESSAGE_TYPE__ROLE;

  /**
   * The number of structural features of the '<em>Receiver L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECEIVER_L_FEATURE_COUNT = MESSAGE_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceLImpl <em>Choice L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ChoiceLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoiceL()
   * @generated
   */
  int CHOICE_L = 26;

  /**
   * The feature id for the '<em><b>Role Making Choice</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_L__ROLE_MAKING_CHOICE = 0;

  /**
   * The feature id for the '<em><b>Branches</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_L__BRANCHES = 1;

  /**
   * The number of structural features of the '<em>Choice L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_L_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachLImpl <em>For Each L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.globalTypes.myDsl.impl.ForEachLImpl
   * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEachL()
   * @generated
   */
  int FOR_EACH_L = 27;

  /**
   * The feature id for the '<em><b>Each Role</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L__EACH_ROLE = 0;

  /**
   * The feature id for the '<em><b>Roleset</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L__ROLESET = 1;

  /**
   * The feature id for the '<em><b>Refrole</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L__REFROLE = 2;

  /**
   * The feature id for the '<em><b>Branch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L__BRANCH = 3;

  /**
   * The feature id for the '<em><b>Protocol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L__PROTOCOL = 4;

  /**
   * The number of structural features of the '<em>For Each L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_L_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.globalTypes.myDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Model#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.Model#getProtocol()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.GlobalProtocol <em>Global Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Global Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.GlobalProtocol
   * @generated
   */
  EClass getGlobalProtocol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.GlobalProtocol#getProtocolName <em>Protocol Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol Name</em>'.
   * @see org.xtext.globalTypes.myDsl.GlobalProtocol#getProtocolName()
   * @see #getGlobalProtocol()
   * @generated
   */
  EAttribute getGlobalProtocol_ProtocolName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.GlobalProtocol#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.GlobalProtocol#getRoles()
   * @see #getGlobalProtocol()
   * @generated
   */
  EReference getGlobalProtocol_Roles();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.GlobalProtocol#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.GlobalProtocol#getProtocol()
   * @see #getGlobalProtocol()
   * @generated
   */
  EReference getGlobalProtocol_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Roles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.Roles
   * @generated
   */
  EClass getRoles();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Roles#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.Roles#getRoles()
   * @see #getRoles()
   * @generated
   */
  EReference getRoles_Roles();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Role <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.Role
   * @generated
   */
  EClass getRole();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Role#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globalTypes.myDsl.Role#getName()
   * @see #getRole()
   * @generated
   */
  EAttribute getRole_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.RoleOne <em>Role One</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role One</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleOne
   * @generated
   */
  EClass getRoleOne();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.RoleSet <em>Role Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Role Set</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleSet
   * @generated
   */
  EClass getRoleSet();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.RoleSet#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.globalTypes.myDsl.RoleSet#getRef()
   * @see #getRoleSet()
   * @generated
   */
  EReference getRoleSet_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Protocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.Protocol
   * @generated
   */
  EClass getProtocol();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Protocol#getBegin <em>Begin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Begin</em>'.
   * @see org.xtext.globalTypes.myDsl.Protocol#getBegin()
   * @see #getProtocol()
   * @generated
   */
  EReference getProtocol_Begin();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.EndProtocol <em>End Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.EndProtocol
   * @generated
   */
  EClass getEndProtocol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.EndProtocol#getEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see org.xtext.globalTypes.myDsl.EndProtocol#getEnd()
   * @see #getEndProtocol()
   * @generated
   */
  EAttribute getEndProtocol_End();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Recursion <em>Recursion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recursion</em>'.
   * @see org.xtext.globalTypes.myDsl.Recursion
   * @generated
   */
  EClass getRecursion();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Recursion#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globalTypes.myDsl.Recursion#getName()
   * @see #getRecursion()
   * @generated
   */
  EAttribute getRecursion_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.Recursion#getRecProtocol <em>Rec Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rec Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.Recursion#getRecProtocol()
   * @see #getRecursion()
   * @generated
   */
  EReference getRecursion_RecProtocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.CloseRecursion <em>Close Recursion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close Recursion</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursion
   * @generated
   */
  EClass getCloseRecursion();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.CloseRecursion#getRecursionVariable <em>Recursion Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Recursion Variable</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursion#getRecursionVariable()
   * @see #getCloseRecursion()
   * @generated
   */
  EReference getCloseRecursion_RecursionVariable();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ForEach <em>For Each</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Each</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach
   * @generated
   */
  EClass getForEach();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEach#getLoopRole <em>Loop Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Loop Role</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getLoopRole()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_LoopRole();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ForEach#getRoleset <em>Roleset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Roleset</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getRoleset()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Roleset();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ForEach#getRefRole <em>Ref Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Role</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getRefRole()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_RefRole();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEach#getForBody <em>For Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>For Body</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getForBody()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_ForBody();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEach#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEach#getProtocol()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Choice#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice#getRole()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Role();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.Choice#getBranches <em>Branches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Branches</em>'.
   * @see org.xtext.globalTypes.myDsl.Choice#getBranches()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Branches();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Message <em>Message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message</em>'.
   * @see org.xtext.globalTypes.myDsl.Message
   * @generated
   */
  EClass getMessage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.Message#getMessageType <em>Message Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message Type</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getMessageType()
   * @see #getMessage()
   * @generated
   */
  EAttribute getMessage_MessageType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Message#getSender <em>Sender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sender</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getSender()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Sender();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.Message#getReceiver <em>Receiver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Receiver</em>'.
   * @see org.xtext.globalTypes.myDsl.Message#getReceiver()
   * @see #getMessage()
   * @generated
   */
  EReference getMessage_Receiver();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageNormal <em>Message Normal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Normal</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormal
   * @generated
   */
  EClass getMessageNormal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.MessageNormal#getPayload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Payload</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormal#getPayload()
   * @see #getMessageNormal()
   * @generated
   */
  EReference getMessageNormal_Payload();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.MessageNormal#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormal#getProtocol()
   * @see #getMessageNormal()
   * @generated
   */
  EReference getMessageNormal_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageQuit <em>Message Quit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Quit</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageQuit
   * @generated
   */
  EClass getMessageQuit();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.Payload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Payload</em>'.
   * @see org.xtext.globalTypes.myDsl.Payload
   * @generated
   */
  EClass getPayload();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.globalTypes.myDsl.Payload#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see org.xtext.globalTypes.myDsl.Payload#getTypes()
   * @see #getPayload()
   * @generated
   */
  EAttribute getPayload_Types();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.LocalProtocol <em>Local Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Local Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.LocalProtocol
   * @generated
   */
  EClass getLocalProtocol();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.LocalProtocol#getProtocolName <em>Protocol Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Protocol Name</em>'.
   * @see org.xtext.globalTypes.myDsl.LocalProtocol#getProtocolName()
   * @see #getLocalProtocol()
   * @generated
   */
  EAttribute getLocalProtocol_ProtocolName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.LocalProtocol#getProjectedRole <em>Projected Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Projected Role</em>'.
   * @see org.xtext.globalTypes.myDsl.LocalProtocol#getProjectedRole()
   * @see #getLocalProtocol()
   * @generated
   */
  EReference getLocalProtocol_ProjectedRole();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.LocalProtocol#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Roles</em>'.
   * @see org.xtext.globalTypes.myDsl.LocalProtocol#getRoles()
   * @see #getLocalProtocol()
   * @generated
   */
  EReference getLocalProtocol_Roles();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.LocalProtocol#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.LocalProtocol#getProtocol()
   * @see #getLocalProtocol()
   * @generated
   */
  EReference getLocalProtocol_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ProtocolL <em>Protocol L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Protocol L</em>'.
   * @see org.xtext.globalTypes.myDsl.ProtocolL
   * @generated
   */
  EClass getProtocolL();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ProtocolL#getBegin <em>Begin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Begin</em>'.
   * @see org.xtext.globalTypes.myDsl.ProtocolL#getBegin()
   * @see #getProtocolL()
   * @generated
   */
  EReference getProtocolL_Begin();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.RecursionL <em>Recursion L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recursion L</em>'.
   * @see org.xtext.globalTypes.myDsl.RecursionL
   * @generated
   */
  EClass getRecursionL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.RecursionL#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.globalTypes.myDsl.RecursionL#getName()
   * @see #getRecursionL()
   * @generated
   */
  EAttribute getRecursionL_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.RecursionL#getRecProtocol <em>Rec Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rec Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.RecursionL#getRecProtocol()
   * @see #getRecursionL()
   * @generated
   */
  EReference getRecursionL_RecProtocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.CloseRecursionL <em>Close Recursion L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Close Recursion L</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursionL
   * @generated
   */
  EClass getCloseRecursionL();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.CloseRecursionL#getRecursionVariable <em>Recursion Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Recursion Variable</em>'.
   * @see org.xtext.globalTypes.myDsl.CloseRecursionL#getRecursionVariable()
   * @see #getCloseRecursionL()
   * @generated
   */
  EReference getCloseRecursionL_RecursionVariable();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageL <em>Message L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message L</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageL
   * @generated
   */
  EClass getMessageL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.globalTypes.myDsl.MessageL#getMessageType <em>Message Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Message Type</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageL#getMessageType()
   * @see #getMessageL()
   * @generated
   */
  EAttribute getMessageL_MessageType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.MessageL#getSendReceive <em>Send Receive</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Send Receive</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageL#getSendReceive()
   * @see #getMessageL()
   * @generated
   */
  EReference getMessageL_SendReceive();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageNormalL <em>Message Normal L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Normal L</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormalL
   * @generated
   */
  EClass getMessageNormalL();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.MessageNormalL#getPayload <em>Payload</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Payload</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormalL#getPayload()
   * @see #getMessageNormalL()
   * @generated
   */
  EReference getMessageNormalL_Payload();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.MessageNormalL#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageNormalL#getProtocol()
   * @see #getMessageNormalL()
   * @generated
   */
  EReference getMessageNormalL_Protocol();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageQuitL <em>Message Quit L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Quit L</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageQuitL
   * @generated
   */
  EClass getMessageQuitL();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.MessageType <em>Message Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Type</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageType
   * @generated
   */
  EClass getMessageType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.MessageType#getRole <em>Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role</em>'.
   * @see org.xtext.globalTypes.myDsl.MessageType#getRole()
   * @see #getMessageType()
   * @generated
   */
  EReference getMessageType_Role();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.SenderL <em>Sender L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sender L</em>'.
   * @see org.xtext.globalTypes.myDsl.SenderL
   * @generated
   */
  EClass getSenderL();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ReceiverL <em>Receiver L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Receiver L</em>'.
   * @see org.xtext.globalTypes.myDsl.ReceiverL
   * @generated
   */
  EClass getReceiverL();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ChoiceL <em>Choice L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice L</em>'.
   * @see org.xtext.globalTypes.myDsl.ChoiceL
   * @generated
   */
  EClass getChoiceL();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ChoiceL#getRoleMakingChoice <em>Role Making Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Role Making Choice</em>'.
   * @see org.xtext.globalTypes.myDsl.ChoiceL#getRoleMakingChoice()
   * @see #getChoiceL()
   * @generated
   */
  EReference getChoiceL_RoleMakingChoice();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.globalTypes.myDsl.ChoiceL#getBranches <em>Branches</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Branches</em>'.
   * @see org.xtext.globalTypes.myDsl.ChoiceL#getBranches()
   * @see #getChoiceL()
   * @generated
   */
  EReference getChoiceL_Branches();

  /**
   * Returns the meta object for class '{@link org.xtext.globalTypes.myDsl.ForEachL <em>For Each L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Each L</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL
   * @generated
   */
  EClass getForEachL();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEachL#getEachRole <em>Each Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Each Role</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL#getEachRole()
   * @see #getForEachL()
   * @generated
   */
  EReference getForEachL_EachRole();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ForEachL#getRoleset <em>Roleset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Roleset</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL#getRoleset()
   * @see #getForEachL()
   * @generated
   */
  EReference getForEachL_Roleset();

  /**
   * Returns the meta object for the reference '{@link org.xtext.globalTypes.myDsl.ForEachL#getRefrole <em>Refrole</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Refrole</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL#getRefrole()
   * @see #getForEachL()
   * @generated
   */
  EReference getForEachL_Refrole();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEachL#getBranch <em>Branch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Branch</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL#getBranch()
   * @see #getForEachL()
   * @generated
   */
  EReference getForEachL_Branch();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.globalTypes.myDsl.ForEachL#getProtocol <em>Protocol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Protocol</em>'.
   * @see org.xtext.globalTypes.myDsl.ForEachL#getProtocol()
   * @see #getForEachL()
   * @generated
   */
  EReference getForEachL_Protocol();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ModelImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__PROTOCOL = eINSTANCE.getModel_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.GlobalProtocolImpl <em>Global Protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.GlobalProtocolImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getGlobalProtocol()
     * @generated
     */
    EClass GLOBAL_PROTOCOL = eINSTANCE.getGlobalProtocol();

    /**
     * The meta object literal for the '<em><b>Protocol Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GLOBAL_PROTOCOL__PROTOCOL_NAME = eINSTANCE.getGlobalProtocol_ProtocolName();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GLOBAL_PROTOCOL__ROLES = eINSTANCE.getGlobalProtocol_Roles();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GLOBAL_PROTOCOL__PROTOCOL = eINSTANCE.getGlobalProtocol_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RolesImpl <em>Roles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RolesImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoles()
     * @generated
     */
    EClass ROLES = eINSTANCE.getRoles();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLES__ROLES = eINSTANCE.getRoles_Roles();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleImpl <em>Role</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRole()
     * @generated
     */
    EClass ROLE = eINSTANCE.getRole();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROLE__NAME = eINSTANCE.getRole_Name();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleOneImpl <em>Role One</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleOneImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleOne()
     * @generated
     */
    EClass ROLE_ONE = eINSTANCE.getRoleOne();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RoleSetImpl <em>Role Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RoleSetImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRoleSet()
     * @generated
     */
    EClass ROLE_SET = eINSTANCE.getRoleSet();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROLE_SET__REF = eINSTANCE.getRoleSet_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolImpl <em>Protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ProtocolImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocol()
     * @generated
     */
    EClass PROTOCOL = eINSTANCE.getProtocol();

    /**
     * The meta object literal for the '<em><b>Begin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOL__BEGIN = eINSTANCE.getProtocol_Begin();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.EndProtocolImpl <em>End Protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.EndProtocolImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getEndProtocol()
     * @generated
     */
    EClass END_PROTOCOL = eINSTANCE.getEndProtocol();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_PROTOCOL__END = eINSTANCE.getEndProtocol_End();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionImpl <em>Recursion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RecursionImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursion()
     * @generated
     */
    EClass RECURSION = eINSTANCE.getRecursion();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECURSION__NAME = eINSTANCE.getRecursion_Name();

    /**
     * The meta object literal for the '<em><b>Rec Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECURSION__REC_PROTOCOL = eINSTANCE.getRecursion_RecProtocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl <em>Close Recursion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursion()
     * @generated
     */
    EClass CLOSE_RECURSION = eINSTANCE.getCloseRecursion();

    /**
     * The meta object literal for the '<em><b>Recursion Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLOSE_RECURSION__RECURSION_VARIABLE = eINSTANCE.getCloseRecursion_RecursionVariable();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ForEachImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEach()
     * @generated
     */
    EClass FOR_EACH = eINSTANCE.getForEach();

    /**
     * The meta object literal for the '<em><b>Loop Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__LOOP_ROLE = eINSTANCE.getForEach_LoopRole();

    /**
     * The meta object literal for the '<em><b>Roleset</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__ROLESET = eINSTANCE.getForEach_Roleset();

    /**
     * The meta object literal for the '<em><b>Ref Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__REF_ROLE = eINSTANCE.getForEach_RefRole();

    /**
     * The meta object literal for the '<em><b>For Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__FOR_BODY = eINSTANCE.getForEach_ForBody();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__PROTOCOL = eINSTANCE.getForEach_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ChoiceImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__ROLE = eINSTANCE.getChoice_Role();

    /**
     * The meta object literal for the '<em><b>Branches</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__BRANCHES = eINSTANCE.getChoice_Branches();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageImpl <em>Message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getMessage();

    /**
     * The meta object literal for the '<em><b>Message Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MESSAGE_TYPE = eINSTANCE.getMessage_MessageType();

    /**
     * The meta object literal for the '<em><b>Sender</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__SENDER = eINSTANCE.getMessage_Sender();

    /**
     * The meta object literal for the '<em><b>Receiver</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE__RECEIVER = eINSTANCE.getMessage_Receiver();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageNormalImpl <em>Message Normal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageNormalImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageNormal()
     * @generated
     */
    EClass MESSAGE_NORMAL = eINSTANCE.getMessageNormal();

    /**
     * The meta object literal for the '<em><b>Payload</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_NORMAL__PAYLOAD = eINSTANCE.getMessageNormal_Payload();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_NORMAL__PROTOCOL = eINSTANCE.getMessageNormal_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageQuitImpl <em>Message Quit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageQuitImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageQuit()
     * @generated
     */
    EClass MESSAGE_QUIT = eINSTANCE.getMessageQuit();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.PayloadImpl <em>Payload</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.PayloadImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getPayload()
     * @generated
     */
    EClass PAYLOAD = eINSTANCE.getPayload();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAYLOAD__TYPES = eINSTANCE.getPayload_Types();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.LocalProtocolImpl <em>Local Protocol</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.LocalProtocolImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getLocalProtocol()
     * @generated
     */
    EClass LOCAL_PROTOCOL = eINSTANCE.getLocalProtocol();

    /**
     * The meta object literal for the '<em><b>Protocol Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOCAL_PROTOCOL__PROTOCOL_NAME = eINSTANCE.getLocalProtocol_ProtocolName();

    /**
     * The meta object literal for the '<em><b>Projected Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCAL_PROTOCOL__PROJECTED_ROLE = eINSTANCE.getLocalProtocol_ProjectedRole();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCAL_PROTOCOL__ROLES = eINSTANCE.getLocalProtocol_Roles();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOCAL_PROTOCOL__PROTOCOL = eINSTANCE.getLocalProtocol_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ProtocolLImpl <em>Protocol L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ProtocolLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getProtocolL()
     * @generated
     */
    EClass PROTOCOL_L = eINSTANCE.getProtocolL();

    /**
     * The meta object literal for the '<em><b>Begin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROTOCOL_L__BEGIN = eINSTANCE.getProtocolL_Begin();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.RecursionLImpl <em>Recursion L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.RecursionLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getRecursionL()
     * @generated
     */
    EClass RECURSION_L = eINSTANCE.getRecursionL();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECURSION_L__NAME = eINSTANCE.getRecursionL_Name();

    /**
     * The meta object literal for the '<em><b>Rec Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RECURSION_L__REC_PROTOCOL = eINSTANCE.getRecursionL_RecProtocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.CloseRecursionLImpl <em>Close Recursion L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.CloseRecursionLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getCloseRecursionL()
     * @generated
     */
    EClass CLOSE_RECURSION_L = eINSTANCE.getCloseRecursionL();

    /**
     * The meta object literal for the '<em><b>Recursion Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLOSE_RECURSION_L__RECURSION_VARIABLE = eINSTANCE.getCloseRecursionL_RecursionVariable();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageLImpl <em>Message L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageL()
     * @generated
     */
    EClass MESSAGE_L = eINSTANCE.getMessageL();

    /**
     * The meta object literal for the '<em><b>Message Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_L__MESSAGE_TYPE = eINSTANCE.getMessageL_MessageType();

    /**
     * The meta object literal for the '<em><b>Send Receive</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_L__SEND_RECEIVE = eINSTANCE.getMessageL_SendReceive();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageNormalLImpl <em>Message Normal L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageNormalLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageNormalL()
     * @generated
     */
    EClass MESSAGE_NORMAL_L = eINSTANCE.getMessageNormalL();

    /**
     * The meta object literal for the '<em><b>Payload</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_NORMAL_L__PAYLOAD = eINSTANCE.getMessageNormalL_Payload();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_NORMAL_L__PROTOCOL = eINSTANCE.getMessageNormalL_Protocol();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageQuitLImpl <em>Message Quit L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageQuitLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageQuitL()
     * @generated
     */
    EClass MESSAGE_QUIT_L = eINSTANCE.getMessageQuitL();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.MessageTypeImpl <em>Message Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.MessageTypeImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getMessageType()
     * @generated
     */
    EClass MESSAGE_TYPE = eINSTANCE.getMessageType();

    /**
     * The meta object literal for the '<em><b>Role</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_TYPE__ROLE = eINSTANCE.getMessageType_Role();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.SenderLImpl <em>Sender L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.SenderLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getSenderL()
     * @generated
     */
    EClass SENDER_L = eINSTANCE.getSenderL();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ReceiverLImpl <em>Receiver L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ReceiverLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getReceiverL()
     * @generated
     */
    EClass RECEIVER_L = eINSTANCE.getReceiverL();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ChoiceLImpl <em>Choice L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ChoiceLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getChoiceL()
     * @generated
     */
    EClass CHOICE_L = eINSTANCE.getChoiceL();

    /**
     * The meta object literal for the '<em><b>Role Making Choice</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_L__ROLE_MAKING_CHOICE = eINSTANCE.getChoiceL_RoleMakingChoice();

    /**
     * The meta object literal for the '<em><b>Branches</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE_L__BRANCHES = eINSTANCE.getChoiceL_Branches();

    /**
     * The meta object literal for the '{@link org.xtext.globalTypes.myDsl.impl.ForEachLImpl <em>For Each L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.globalTypes.myDsl.impl.ForEachLImpl
     * @see org.xtext.globalTypes.myDsl.impl.MyDslPackageImpl#getForEachL()
     * @generated
     */
    EClass FOR_EACH_L = eINSTANCE.getForEachL();

    /**
     * The meta object literal for the '<em><b>Each Role</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_L__EACH_ROLE = eINSTANCE.getForEachL_EachRole();

    /**
     * The meta object literal for the '<em><b>Roleset</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_L__ROLESET = eINSTANCE.getForEachL_Roleset();

    /**
     * The meta object literal for the '<em><b>Refrole</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_L__REFROLE = eINSTANCE.getForEachL_Refrole();

    /**
     * The meta object literal for the '<em><b>Branch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_L__BRANCH = eINSTANCE.getForEachL_Branch();

    /**
     * The meta object literal for the '<em><b>Protocol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH_L__PROTOCOL = eINSTANCE.getForEachL_Protocol();

  }

} //MyDslPackage
