/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Role Set L</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globalTypes.myDsl.RoleSetL#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getRoleSetL()
 * @model
 * @generated
 */
public interface RoleSetL extends RoleL
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(RoleOneL)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getRoleSetL_Ref()
   * @model
   * @generated
   */
  RoleOneL getRef();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.RoleSetL#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(RoleOneL value);

} // RoleSetL
