/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Role One L</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getRoleOneL()
 * @model
 * @generated
 */
public interface RoleOneL extends RoleL
{
} // RoleOneL
