/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Role Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.globalTypes.myDsl.RoleSet#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.xtext.globalTypes.myDsl.MyDslPackage#getRoleSet()
 * @model
 * @generated
 */
public interface RoleSet extends Role
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(RoleOne)
   * @see org.xtext.globalTypes.myDsl.MyDslPackage#getRoleSet_Ref()
   * @model
   * @generated
   */
  RoleOne getRef();

  /**
   * Sets the value of the '{@link org.xtext.globalTypes.myDsl.RoleSet#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(RoleOne value);

} // RoleSet
