/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.generator;

import com.google.common.base.Objects;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.xtext.globalTypes.myDsl.Choice;
import org.xtext.globalTypes.myDsl.CloseRecursion;
import org.xtext.globalTypes.myDsl.Definition;
import org.xtext.globalTypes.myDsl.EndProtocol;
import org.xtext.globalTypes.myDsl.ForEach;
import org.xtext.globalTypes.myDsl.GlobalProtocol;
import org.xtext.globalTypes.myDsl.LocalProtocol;
import org.xtext.globalTypes.myDsl.Message;
import org.xtext.globalTypes.myDsl.MessageNormal;
import org.xtext.globalTypes.myDsl.Model;
import org.xtext.globalTypes.myDsl.Payload;
import org.xtext.globalTypes.myDsl.Protocol;
import org.xtext.globalTypes.myDsl.Recursion;
import org.xtext.globalTypes.myDsl.Role;
import org.xtext.globalTypes.myDsl.RoleOne;
import org.xtext.globalTypes.myDsl.RoleSet;
import org.xtext.globalTypes.myDsl.Roles;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    EObject _head = IterableExtensions.<EObject>head(resource.getContents());
    Model model = ((Model) _head);
    EObject _protocol = model.getProtocol();
    if ((_protocol instanceof GlobalProtocol)) {
      EObject _protocol_1 = model.getProtocol();
      GlobalProtocol globalProtocol = ((GlobalProtocol) _protocol_1);
      EList<Role> _roles = globalProtocol.getRoles().getRoles();
      for (final Role r : _roles) {
        {
          String _name = r.getName();
          String _plus = ("LOCAL in " + _name);
          System.out.println(_plus);
          String _name_1 = r.getName();
          String _plus_1 = ("../src/local/local_" + _name_1);
          String _plus_2 = (_plus_1 + ".jglobal");
          fsa.generateFile(_plus_2, this.project(globalProtocol, model.getDefinitions(), r));
          String _name_2 = r.getName();
          String _plus_3 = ("END LOCAL on " + _name_2);
          System.out.println(_plus_3);
        }
      }
    } else {
      EObject _protocol_2 = model.getProtocol();
      LocalProtocol localProtocol = ((LocalProtocol) _protocol_2);
      System.out.println("JADE");
      Role _projectedRole = localProtocol.getProjectedRole();
      String _plus = ("jade/jade" + _projectedRole);
      String _plus_1 = (_plus + ".txt");
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("aaa");
      fsa.generateFile(_plus_1, _builder);
    }
  }

  public CharSequence project(final GlobalProtocol p, final EList<Definition> definitions, final Role role) {
    StringConcatenation _builder = new StringConcatenation();
    {
      for(final Definition d : definitions) {
        {
          String _type = d.getType();
          boolean _equals = Objects.equal(_type, "@proposition");
          if (_equals) {
            String _type_1 = d.getType();
            _builder.append(_type_1);
            _builder.append(" ");
            String _name = d.getName();
            _builder.append(_name);
            _builder.newLineIfNotEmpty();
          }
        }
        {
          String _type_2 = d.getType();
          boolean _equals_1 = Objects.equal(_type_2, "@predicate");
          if (_equals_1) {
            String _type_3 = d.getType();
            _builder.append(_type_3);
            _builder.append(" ");
            String _name_1 = d.getName();
            _builder.append(_name_1);
            _builder.append("(");
            {
              EList<String> _types = d.getTypes();
              boolean _hasElements = false;
              for(final String t : _types) {
                if (!_hasElements) {
                  _hasElements = true;
                } else {
                  _builder.appendImmediate(", ", "");
                }
                _builder.append(t);
              }
            }
            _builder.append(")");
            _builder.newLineIfNotEmpty();
          }
        }
        {
          String _type_4 = d.getType();
          boolean _equals_2 = Objects.equal(_type_4, "@action");
          if (_equals_2) {
            {
              int _length = ((Object[])Conversions.unwrapArray(d.getTypes(), Object.class)).length;
              boolean _notEquals = (_length != 0);
              if (_notEquals) {
                String _type_5 = d.getType();
                _builder.append(_type_5);
                _builder.append(" ");
                String _name_2 = d.getName();
                _builder.append(_name_2);
                _builder.append("(");
                {
                  EList<String> _types_1 = d.getTypes();
                  boolean _hasElements_1 = false;
                  for(final String t_1 : _types_1) {
                    if (!_hasElements_1) {
                      _hasElements_1 = true;
                    } else {
                      _builder.appendImmediate(", ", "");
                    }
                    _builder.append(t_1);
                  }
                }
                _builder.append(")");
                _builder.newLineIfNotEmpty();
              } else {
                String _type_6 = d.getType();
                _builder.append(_type_6);
                _builder.append(" ");
                String _name_3 = d.getName();
                _builder.append(_name_3);
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
      }
    }
    _builder.newLine();
    _builder.append("local protocol ");
    String _protocolName = p.getProtocolName();
    _builder.append(_protocolName);
    _builder.append(" at ");
    CharSequence _projectOn = this.projectOn(role, role);
    _builder.append(_projectOn);
    _builder.append("(");
    CharSequence _projectOn_1 = this.projectOn(p.getRoles(), role);
    _builder.append(_projectOn_1);
    _builder.append(") {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    CharSequence _projectOn_2 = this.projectOn(p.getProtocol(), role);
    _builder.append(_projectOn_2, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _projectOn(final Protocol protocol, final Role role) {
    StringConcatenation _builder = new StringConcatenation();
    String _name = role.getName();
    String _plus = ("Project on here " + _name);
    System.out.println(_plus);
    _builder.newLineIfNotEmpty();
    Object _projectOn = this.projectOn(protocol.getBegin(), role);
    _builder.append(_projectOn);
    return _builder;
  }

  protected CharSequence _projectOn(final Roles roles, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    {
      final Function1<Role, Boolean> _function = (Role it) -> {
        boolean _equals = it.getName().equals(r.getName());
        return Boolean.valueOf((!_equals));
      };
      Iterable<Role> _filter = IterableExtensions.<Role>filter(roles.getRoles(), _function);
      boolean _hasElements = false;
      for(final Role role : _filter) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        Object _projectOn = this.projectOn(role, r);
        _builder.append(_projectOn);
      }
    }
    return _builder;
  }

  protected CharSequence _projectOn(final Role role, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((role instanceof RoleOne)) {
        _builder.append("role ");
        String _name = ((RoleOne)role).getName();
        _builder.append(_name);
      } else {
        _builder.append("roleset ");
        String _name_1 = role.getName();
        _builder.append(_name_1);
        _builder.append(":");
        String _name_2 = ((RoleSet) role).getRef().getName();
        _builder.append(_name_2);
      }
    }
    return _builder;
  }

  /**
   * projection of a message on a role with differentiation between normal messages
   * and quit messages. In the first case the protocol continues.
   * 
   * m: Message (superclass of MessageNormal and MessageQuit)
   * r: role to project on
   * 
   * 
   * (\ud835\udc65 → q ℓQuit ) ↾\ud835\udf0c q = \ud835\udc65 ? ℓQuit
   * (\ud835\udc65 → q ℓQuit ) ↾\ud835\udf0cR = q!ℓQuit
   * (\ud835\udc65 → q ℓQuit ) ↾\ud835\udf0c p = End
   */
  protected CharSequence _projectOn(final Message m, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((m instanceof MessageNormal)) {
        {
          String _name = ((MessageNormal)m).getSender().getName();
          String _name_1 = r.getName();
          boolean _equals = Objects.equal(_name, _name_1);
          if (_equals) {
            String _name_2 = ((MessageNormal)m).getMessageType().getName();
            _builder.append(_name_2);
            _builder.append("(");
            CharSequence _printPayload = this.printPayload(((MessageNormal)m).getPayload());
            _builder.append(_printPayload);
            _builder.append(") to ");
            String _name_3 = ((MessageNormal)m).getReceiver().getName();
            _builder.append(_name_3);
            _builder.append(".");
            _builder.newLineIfNotEmpty();
          } else {
            {
              String _name_4 = ((MessageNormal)m).getReceiver().getName();
              String _name_5 = r.getName();
              boolean _equals_1 = Objects.equal(_name_4, _name_5);
              if (_equals_1) {
                String _name_6 = ((MessageNormal)m).getMessageType().getName();
                _builder.append(_name_6);
                _builder.append("(");
                CharSequence _printPayload_1 = this.printPayload(((MessageNormal)m).getPayload());
                _builder.append(_printPayload_1);
                _builder.append(") from ");
                String _name_7 = ((MessageNormal)m).getSender().getName();
                _builder.append(_name_7);
                _builder.append(".");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        Object _projectOn = this.projectOn(((MessageNormal)m).getProtocol(), r);
        _builder.append(_projectOn);
        _builder.newLineIfNotEmpty();
      } else {
        {
          String _name_8 = m.getSender().getName();
          String _name_9 = r.getName();
          boolean _equals_2 = Objects.equal(_name_8, _name_9);
          if (_equals_2) {
            _builder.append("QUIT() to ");
            String _name_10 = m.getReceiver().getName();
            _builder.append(_name_10);
            _builder.newLineIfNotEmpty();
          } else {
            {
              String _name_11 = m.getReceiver().getName();
              String _name_12 = r.getName();
              boolean _equals_3 = Objects.equal(_name_11, _name_12);
              if (_equals_3) {
                _builder.append("QUIT() from ");
                String _name_13 = m.getSender().getName();
                _builder.append(_name_13);
                _builder.newLineIfNotEmpty();
              } else {
                _builder.append("End");
                _builder.newLine();
              }
            }
          }
        }
      }
    }
    return _builder;
  }

  /**
   * p → Q{ ℓ\ud835\udc56⟨S\ud835\udc56⟩.G\ud835\udc56 }\ud835\udc56∈\ud835\udc3c ↾\ud835\udf0c R = Q!{ ℓ\ud835\udc56⟨S\ud835\udc56⟩.G\ud835\udc56 ↾\ud835\udf0c R }\ud835\udc56∈\ud835\udc3c if RoleSet(p, \ud835\udf0c) = R
   * p → Q{ ℓ\ud835\udc56⟨S\ud835\udc56⟩.G\ud835\udc56 }\ud835\udc56∈\ud835\udc3c ↾\ud835\udf0c R = p?{ ℓ\ud835\udc56⟨S\ud835\udc56⟩.G\ud835\udc56 ↾\ud835\udf0c R }\ud835\udc56∈\ud835\udc3c if RoleSet(Q, \ud835\udf0c) = R
   * p → Q{ ℓ\ud835\udc56⟨S\ud835\udc56⟩.G\ud835\udc56 }\ud835\udc56∈\ud835\udc3c ↾\ud835\udf0c R = ⨆︀\ud835\udc56∈\ud835\udc3c G\ud835\udc56 ↾\ud835\udf0c R //merge
   */
  protected CharSequence _projectOn(final Choice c, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((Objects.equal(c.getBranches().get(0).getReceiver(), r) || Objects.equal(c.getBranches().get(0).getSender(), r))) {
        _builder.append("choice at ");
        String _name = c.getRole().getName();
        _builder.append(_name);
        _builder.append("{");
        _builder.newLineIfNotEmpty();
        {
          int _length = ((Object[])Conversions.unwrapArray(c.getBranches(), Object.class)).length;
          int _minus = (_length - 1);
          IntegerRange _upTo = new IntegerRange(0, _minus);
          boolean _hasElements = false;
          for(final int i : _upTo) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(" or {", "");
            }
            _builder.append("\t");
            Object _projectOn = this.projectOn(c.getBranches().get(i), r);
            _builder.append(_projectOn, "\t");
            _builder.newLineIfNotEmpty();
            _builder.append("}");
            _builder.newLine();
          }
        }
      } else {
        CharSequence _merge = MergeUtil.merge(c, r);
        _builder.append(_merge);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  public CharSequence safeProjectOn(final Choice c, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("choice at ");
    String _name = c.getRole().getName();
    _builder.append(_name);
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    {
      int _length = ((Object[])Conversions.unwrapArray(c.getBranches(), Object.class)).length;
      int _minus = (_length - 1);
      IntegerRange _upTo = new IntegerRange(0, _minus);
      boolean _hasElements = false;
      for(final int i : _upTo) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(" or {", "");
        }
        _builder.append("\t");
        CharSequence _projectOn = this.projectOn(c.getBranches().get(i), r);
        _builder.append(_projectOn, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder;
  }

  protected CharSequence _projectOn(final Recursion rec, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("rec ");
    String _name = rec.getName();
    _builder.append(_name);
    _builder.append(": {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    Object _projectOn = this.projectOn(rec.getRecProtocol(), r);
    _builder.append(_projectOn, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _projectOn(final CloseRecursion recEnd, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("loop ");
    String _name = recEnd.getRecursionVariable().getName();
    _builder.append(_name);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _projectOn(final ForEach each, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    {
      RoleSet _roleset = each.getRoleset();
      boolean _equals = Objects.equal(_roleset, r);
      if (_equals) {
        System.out.println("seq foreach start");
        _builder.newLineIfNotEmpty();
        CharSequence _seqOn = this.seqOn(each.getForBody(), each.getLoopRole(), each.getRoleset(), each.getProtocol());
        _builder.append(_seqOn);
        _builder.newLineIfNotEmpty();
      }
    }
    {
      RoleOne _refRole = each.getRefRole();
      boolean _equals_1 = Objects.equal(_refRole, r);
      if (_equals_1) {
        System.out.println("project foreach start");
        _builder.newLineIfNotEmpty();
        _builder.append("foreach role ");
        String _name = each.getLoopRole().getName();
        _builder.append(_name);
        _builder.append(":<");
        String _name_1 = each.getRoleset().getName();
        _builder.append(_name_1);
        _builder.append(",");
        String _name_2 = each.getRefRole().getName();
        _builder.append(_name_2);
        _builder.append(">{");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        Object _projectOn = this.projectOn(each.getForBody(), r);
        _builder.append(_projectOn, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("};");
        _builder.newLine();
        Object _projectOn_1 = this.projectOn(each.getProtocol(), r);
        _builder.append(_projectOn_1);
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder;
  }

  protected CharSequence _projectOn(final EndProtocol end, final Role r) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("End");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _seqOn(final Protocol protocol, final Role role, final Role roleset, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    Object _seqOn = this.seqOn(protocol.getBegin(), role, roleset, p);
    _builder.append(_seqOn);
    return _builder;
  }

  protected CharSequence _seqOn(final Message m, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    Definition _messageType = m.getMessageType();
    String _plus = ("seq message " + _messageType);
    System.out.println(_plus);
    _builder.newLineIfNotEmpty();
    {
      if ((m instanceof MessageNormal)) {
        {
          String _name = ((MessageNormal)m).getSender().getName();
          String _name_1 = r.getName();
          boolean _equals = Objects.equal(_name, _name_1);
          if (_equals) {
            String _name_2 = ((MessageNormal)m).getMessageType().getName();
            _builder.append(_name_2);
            _builder.append("(");
            CharSequence _printPayload = this.printPayload(((MessageNormal)m).getPayload());
            _builder.append(_printPayload);
            _builder.append(") to ");
            String _name_3 = ((MessageNormal)m).getReceiver().getName();
            _builder.append(_name_3);
            _builder.append(".");
            _builder.newLineIfNotEmpty();
          } else {
            {
              String _name_4 = ((MessageNormal)m).getReceiver().getName();
              String _name_5 = r.getName();
              boolean _equals_1 = Objects.equal(_name_4, _name_5);
              if (_equals_1) {
                String _name_6 = ((MessageNormal)m).getMessageType().getName();
                _builder.append(_name_6);
                _builder.append("(");
                CharSequence _printPayload_1 = this.printPayload(((MessageNormal)m).getPayload());
                _builder.append(_printPayload_1);
                _builder.append(") from ");
                String _name_7 = ((MessageNormal)m).getSender().getName();
                _builder.append(_name_7);
                _builder.append(".");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        Object _seqOn = this.seqOn(((MessageNormal)m).getProtocol(), r, rs, p);
        _builder.append(_seqOn);
        _builder.newLineIfNotEmpty();
      } else {
        {
          String _name_8 = m.getSender().getName();
          String _name_9 = r.getName();
          boolean _equals_2 = Objects.equal(_name_8, _name_9);
          if (_equals_2) {
            _builder.append("QUIT() to ");
            String _name_10 = m.getReceiver().getName();
            _builder.append(_name_10);
            _builder.newLineIfNotEmpty();
          } else {
            {
              String _name_11 = m.getReceiver().getName();
              String _name_12 = r.getName();
              boolean _equals_3 = Objects.equal(_name_11, _name_12);
              if (_equals_3) {
                _builder.append("QUIT() from ");
                String _name_13 = m.getSender().getName();
                _builder.append(_name_13);
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
      }
    }
    return _builder;
  }

  protected CharSequence _seqOn(final Choice c, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("choice at ");
    String _name = c.getRole().getName();
    _builder.append(_name);
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    {
      int _length = ((Object[])Conversions.unwrapArray(c.getBranches(), Object.class)).length;
      int _minus = (_length - 1);
      IntegerRange _upTo = new IntegerRange(0, _minus);
      boolean _hasElements = false;
      for(final int i : _upTo) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(" or {", "");
        }
        _builder.append("\t");
        Object _seqOn = this.seqOn(c.getBranches().get(i), r, rs, p);
        _builder.append(_seqOn, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder;
  }

  protected CharSequence _seqOn(final Recursion rec, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    System.out.println("seq rec");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("rec ");
    String _name = rec.getName();
    _builder.append(_name, "\t");
    _builder.append(": {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    Object _seqOn = this.seqOn(rec.getRecProtocol(), r, rs, p);
    _builder.append(_seqOn, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  protected CharSequence _seqOn(final ForEach f, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    System.out.println("seq for");
    _builder.newLineIfNotEmpty();
    Object _projectOn = this.projectOn(f, rs);
    _builder.append(_projectOn);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _seqOn(final CloseRecursion close, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    Object _projectOn = this.projectOn(close, r);
    _builder.append(_projectOn);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  protected CharSequence _seqOn(final EndProtocol end, final Role r, final Role rs, final Protocol p) {
    StringConcatenation _builder = new StringConcatenation();
    System.out.println("seq end");
    _builder.newLineIfNotEmpty();
    Object _projectOn = this.projectOn(p, rs);
    _builder.append(_projectOn);
    _builder.newLineIfNotEmpty();
    return _builder;
  }

  public CharSequence printPayload(final Payload payload) {
    StringConcatenation _builder = new StringConcatenation();
    {
      if ((payload != null)) {
        {
          EList<String> _types = payload.getTypes();
          boolean _hasElements = false;
          for(final String type : _types) {
            if (!_hasElements) {
              _hasElements = true;
            } else {
              _builder.appendImmediate(", ", "");
            }
            _builder.append(type);
          }
        }
      }
    }
    return _builder;
  }

  public CharSequence projectOn(final EObject c, final Role r) {
    if (c instanceof Choice) {
      return _projectOn((Choice)c, r);
    } else if (c instanceof CloseRecursion) {
      return _projectOn((CloseRecursion)c, r);
    } else if (c instanceof EndProtocol) {
      return _projectOn((EndProtocol)c, r);
    } else if (c instanceof ForEach) {
      return _projectOn((ForEach)c, r);
    } else if (c instanceof Message) {
      return _projectOn((Message)c, r);
    } else if (c instanceof Protocol) {
      return _projectOn((Protocol)c, r);
    } else if (c instanceof Recursion) {
      return _projectOn((Recursion)c, r);
    } else if (c instanceof Role) {
      return _projectOn((Role)c, r);
    } else if (c instanceof Roles) {
      return _projectOn((Roles)c, r);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(c, r).toString());
    }
  }

  public CharSequence seqOn(final EObject c, final Role r, final Role rs, final Protocol p) {
    if (c instanceof Choice) {
      return _seqOn((Choice)c, r, rs, p);
    } else if (c instanceof CloseRecursion) {
      return _seqOn((CloseRecursion)c, r, rs, p);
    } else if (c instanceof EndProtocol) {
      return _seqOn((EndProtocol)c, r, rs, p);
    } else if (c instanceof ForEach) {
      return _seqOn((ForEach)c, r, rs, p);
    } else if (c instanceof Message) {
      return _seqOn((Message)c, r, rs, p);
    } else if (c instanceof Protocol) {
      return _seqOn((Protocol)c, r, rs, p);
    } else if (c instanceof Recursion) {
      return _seqOn((Recursion)c, r, rs, p);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(c, r, rs, p).toString());
    }
  }
}
