/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.globalTypes.myDsl.MessageQuitL;
import org.xtext.globalTypes.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Message Quit L</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MessageQuitLImpl extends MessageLImpl implements MessageQuitL
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MessageQuitLImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MESSAGE_QUIT_L;
  }

} //MessageQuitLImpl
