/**
 * generated by Xtext 2.34.0
 */
package org.xtext.globalTypes.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.globalTypes.myDsl.MyDslPackage;
import org.xtext.globalTypes.myDsl.QuitDefinition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Quit Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class QuitDefinitionImpl extends DefinitionImpl implements QuitDefinition
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QuitDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.QUIT_DEFINITION;
  }

} //QuitDefinitionImpl
